---
title: "GSEA figures"
author: "Mikhail Dozmorov"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: no
  html_document:
    theme: cerulean
    toc: yes
---

```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
# Set up the environment
library(knitr)
opts_chunk$set(cache.path='cache/', fig.path='img/', cache=F, tidy=T, fig.keep='high', echo=F, dpi=100, warnings=F, message=F, comment=NA, warning=F, results='as.is', fig.width = 10, fig.height = 6) #out.width=700, 
library(pander)
panderOptions('table.split.table', Inf)
set.seed(1)
library(dplyr)
options(stringsAsFactors = FALSE)
```

```{r libraries}
# Libraries

library(readxl)
library(cowplot)
library(ggplot2)
library(stringr)
library("ggsci")
library(scales)
scales::show_col(pal_lancet("lanonc")(8))
mycols = pal_lancet("lanonc")(8)
library(forcats)
```

# Settings

```{r settings}
# Data
# data_dir       <- "/Users/mdozmorov/Documents/Data/GoogleDrive/HiC_files/results/manuscript/Tables_WGS_Enrichment"
data_dir       <- "~/Google Drive/My Drive/HiC_files/results/manuscript/Tables_WGS_Enrichment"
# Working directory
fileNameIn1   <- file.path(data_dir, "Tables_WGS_Enrichment.xlsx") # File to save all results of differential expression analysis
fileNameOut1 <- file.path(data_dir, "Figure_WGS_Enrichment.svg")
# Create output folder, if not exists
# if (!dir.exists(file.path(data_dir, "results"))) dir.create(file.path(data_dir, "results"))

max_enrichment_length <- 50 # Maximum length of enrichment descriptions
```

# Visualization

-log10 adjusted p-value interpretation

$$1 = 10^{-1} = 0.1$$
$$1.3 = 10^{-1.3} \approx 0.05$$
$$2 = 10^{-2} = 0.01$$
$$4 = 10^{-4} = 0.0001$$
etc. -log10 adjusted p-value $\ge1$ is acceptable

```{r fig.height=4}
# Sheets with enrichments
all_sheets <- c("DEL.Enrich.C2", "DUP.Enrich.C2")

# Deletions, first two are of interest
mtx1 <- read_xlsx(fileNameIn1, sheet = all_sheets[1])
mtx1 <- mtx1[1:2, ]
# Add -log10 adjusted p-value. -1 - enrichments for deletions face in negative directions
mtx1$log10padj <- -log10(as.numeric(mtx1$p.adjust)) * (-1)

# Duplications, first six are of interest
mtx2 <- read_xlsx(fileNameIn1, sheet = all_sheets[2])
mtx2 <- mtx2[1:6, ]
# Add -log10 adjusted p-value
mtx2$log10padj <- -log10(as.numeric(mtx2$p.adjust))

# Combine them
mtx <- rbind(mtx1, mtx2)
# Add sign variable indicating whether log10padj is negative or positive
mtx[["sign"]] = ifelse(mtx[["log10padj"]] >= 0, "positive", "negative")
# Adjust what name to plot
mtx$enrichment <- str_trunc(mtx$ID, width = max_enrichment_length)

# Actual plotting
# dev.off()
# svg(fileNameOut1, width = 4, height = 6 )

ggplot(data = mtx, aes(x = reorder(enrichment, log10padj), y = log10padj)) +
  # geom_col(aes(fill = log10padj)) +
  geom_col(aes(fill = sign)) +
  # scale_fill_gradient2(low = "blue", high = "red", midpoint = 0) +
  scale_fill_manual(name = "Direction",
                    values = c("positive" = mycols[2], "negative" = mycols[1]), 
                    labels = c("Duplicated", "Deleted")) +
  coord_flip() +
  theme_cowplot() +
  ylab("-log10 adjusted p-value") +
  xlab("Enrichment term") +
  theme(text = element_text(size = 20),
          axis.text = element_text(size = 15),
        legend.position = c(0.45, 0.6))

ggsave(filename = fileNameOut1, width = 10, height = 6)

# dev.off()
```


